### ISSUE TITLE
WebPack instead Browserify

### ISSUE THREAD

**Issue by mtrullasp** [martyjs/marty#214]

**Comment by jhollingworth** [comment]
sorry don't follow. Do you want examples of browserify or do you think we should use webpack internally?

**Comment by engineersamuel** [comment]
I would +1 on Webpack in general.  I've been using webpack for many of my projects for about a year, and the power and flexibility you get with Webpack is next to none: http://webpack.github.io/docs/comparison.html

**Comment by jhollingworth** [comment]
I've not personally used webpack in anger but will investigate and get back to you

**Comment by dariocravero** [comment]
browserify's author [made a great gist](https://gist.github.com/substack/68f8d502be42d5cd4942) comparing the two in depth, the whole thing is worth a read - the comments are very good too :).

The way I see it, browserify is a better guess for a widely used project like Marty since it doesn't make too many assumptions about its eco-system and it keeps concerns separate allowing for greater compositions that suit your needs. My two cents :)

**Comment by jhollingworth** [comment]
Right now I don't think we're going to move to webpack internally. Since marty is built using [umd](https://github.com/umdjs/umd) this shouldn't really affect any library consuming it.

Going to close for now but please re-open if you have some convincing argument for moving to webpack
